export const DIVIDERS = {
  EXTRACTED_RULES:
    '<!-- The following rules are extracted from user-supplied rules files -->',
  GENERATED_BY: '<!-- Generated by cursor-rules-to-claude v1.0.0 -->',
  AUTO_ATTACHED: '<!-- Auto attached rules -->',
  CONDITIONAL_RULES:
    '<!-- The following rules can be requested by agent by reading the filepath directly. -->',
  NO_FRONTMATTER:
    '<!-- The following rules do not have a frontmatter. They are included by default to allow this package to work with multiple different rule types -->',
} as const;
