import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const packageJson = JSON.parse(
  readFileSync(join(__dirname, '..', 'package.json'), 'utf-8')
);

export const DIVIDERS = {
  EXTRACTED_RULES:
    '<!-- The following rules are extracted from user-supplied rules files -->',
  GENERATED_BY: `<!-- Generated by cursor-rules-to-claude v${packageJson.version} -->`,
  AUTO_ATTACHED: '<!-- Auto attached rules -->',
  CONDITIONAL_RULES:
    '<!-- The following rules can be requested by agent by reading the filepath directly. -->',
  NO_FRONTMATTER:
    '<!-- The following rules do not have a frontmatter. They are included by default to allow this package to work with multiple different rule types -->',
} as const;
